config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    resources :pages
  end
  
  get '/pages/:slug', to: 'pages#show', as: 'page'
  
end

app/models/spree/page.rb
module Spree
  class Page < ApplicationRecord

  end
end

app/controllers/spree/admin/pages_controller.rb
module Spree
  module Admin
    class PagesController < ResourceController
      private

      def permitted_resource_params
        params.require(:page).permit(%i[title body slug meta_title meta_description published template])
      end
    end
  end
end

app/controllers/spree/pages_controller.rb
module Spree
  class PagesController < StoreController
    
    def show
      
      #@page=Spree::Page.where(slug: request.path[1..-1]).first
      @page=Spree::Page.where(slug: params[:slug]).first
      if @page.nil? || !@page.published
        error_404
      else 
        @title = @page.meta_title
        render "/pages/templates/#{@page.template}"
      end
    end
    
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/spree/base_helper_decorator.rb
Spree::BaseHelper.module_eval do

    def meta_data
      object = instance_variable_get('@' + controller_name.singularize)
      meta = {}

      if object.is_a? ApplicationRecord
        meta[:keywords] = object.meta_keywords if object[:meta_keywords].present?
        meta[:description] = object.meta_description if object[:meta_description].present?
      end

      if meta[:description].blank? && object.is_a?(Spree::Product)
        meta[:description] = truncate(strip_tags(object.description), length: 160, separator: ' ')
      end
      
      if meta[:keywords].blank? || meta[:description].blank?
        meta.reverse_merge!(keywords: current_store.meta_keywords,
                            description: current_store.meta_description)
      end
      
      if object.is_a?(Spree::Page)
        meta[:description]=object.meta_description
      end
      
      meta
    end

end

app/views/spree/admin/pages/_form.html.erb
<%= render partial: 'spree/shared/error_messages', locals: { target: resource } %>

<%= form_for [:admin, resource] do |f| %>
  <div class="row" data-hook="admin_page_form_fields">

      <div class="form-group">
        <%= f.label :published %>
        <%= f.check_box :published %>
      </div>
      
      <div class="form-group">
        <%= f.label :title %> <span class="required">*</span>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :template %>
        <%= f.text_field :template %>
      </div>

      <div class="form-group">
        <%= f.label :slug %> <span class="required">*</span>
        <%= f.text_field :slug, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :body %> <span class="required">*</span>
        <%= f.text_area :body, rows: 30, class: 'form-control', id: 'summernote' %>
      </div>

      <div class="form-group">
        <%= f.label :meta_title %>
        <%= f.text_field :meta_title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :meta_description %>
        <%= f.text_field :meta_description, class: 'form-control' %>
      </div>
    
    <script>
      $('#summernote').summernote({
        placeholder: 'Текст страницы',
        tabsize: 2,
        height: 500,
        fontNames: ['Roboto', 'Roboto Light', 'Roboto Regular', 'Roboto Bold'],
        fontNamesIgnoreCheck: ['Roboto', 'Roboto Light', 'Roboto Regular', 'Roboto Bold'],
      });
    </script>

  </div>

  <%= render "spree/admin/shared/#{resource.new_record? ? 'new' : 'edit'}_resource_links" %>
<% end %>

app/views/spree/admin/pages/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::Page.model_name.human) %>
<% end %>

<%= render 'form', resource: @page %>

app/views/spree/admin/pages/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Page) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_page), new_object_url, icon: 'plus', class: 'btn-primary', id: 'admin_new_page' %>
<% end %>

<% if @pages.any? %>
  <table class="table" id="listing_pages" data-hook>
    <colgroup>
      <col style="width: 20%">
      <col style="width: 20%">
      <col style="width: 20%">
      <col style="width: 20%">
      <col style="width: 20%">
    </colgroup>
    <thead>
      <tr data-hook="admin_pages_index_headers">
        <th><%= Spree::Page.human_attribute_name(:title) %></th>
        <th><%= Spree::Page.human_attribute_name(:published) %></th>
        <th><%= Spree::Page.human_attribute_name(:template) %></th>
        <th><%= Spree::Page.human_attribute_name(:slug) %></th>
        <th data-hook="admin_pages_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @pages.each do |page| %>
        <tr data-hook="admin_pages_index_rows" class="<%= cycle('odd', 'even') %>" id="<%= dom_id page %>">
          <td><%= page.title %></td>
          <td><%= page.published ? '+' : '-' %></td>
          <td><%= page.template %></td>
          <td><%= page.slug %></td>
          <td class="actions text-right" data-hook="admin_pages_index_row_actions">
            <%= link_to 'Show in app', page_url(page.slug), target: '_blank' %>
            <%= link_to_edit page, no_text: true %>
            <%= link_to_delete page, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-warning no-objects-found">
    <%= Spree.t(:no_resource_found, resource: Spree::Page.model_name.human) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_page_path %>!
  </div>
<% end %>

app/views/spree/admin/pages/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:new_page) %>
<% end %>

<%= render 'form', resource: @page %>

app/views/spree/admin/shared/_pages_menu_item.html.erb
<% if can?(:admin, Spree::Page) %>
  <ul class='nav nav-sidebar'>
    <%= tab Spree::Page, url: spree.admin_pages_url, icon: 'font', label: plural_resource_name(Spree::Page) %>
  </ul>
<% end %>

app/views/spree/pages/_og_meta_tags.html.erb
<% content_for(:head) do %>
  <% page_meta_title = page.meta_title.presence || @title %>
  <meta name="title" content="<%= page_meta_title %>">
  <meta property="og:title" content="<%= page_meta_title %>">
  <meta property="og:description" content="<%= page.meta_description || meta_data[:description] %>">
<% end %>

app/views/spree/pages/show.html.erb
<%= render partial: 'og_meta_tags', locals: { page: @page } %>

<% cache([:v3, @page]) do %>
  <center><h1><%= @page.title %></h1></center>
  <br>
  <div id='page_content'>
    <%= raw @page.body %>
  </div>
<% end %>